---
name: Publish Package

on:
  push:
#    tags:
#      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        # Disabled
        #if: ${{ false }}
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        # Disabled
        #if: ${{ false }}
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
    #      cache: 'pnpm'

    #  - run: npm ci
      - run: npm run build --if-present
    #  - run: npm test
      - run: pnpm publish
    #  - run: npm publish
